modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/Rivmun/SuperFancyCloudsRefabricated/issues"
license = "MIT"

[[mods]]
modId = "sfcr"
version = "${version}"
displayName = "SuperFancyClouds: Rearchitected"
authors = "Rimo"
credits = "Ami-Wishes"
description = '''
A client/server side mod makes your Minecraft sky full of more stereoscopic and dynamic clouds.
'''
logoFile = "icon.png"

[[dependencies.sfcr]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sfcr]]
modId = "minecraft"
mandatory = true
versionRange = "1.19.4"
ordering = "NONE"
side = "BOTH"

[[dependencies.sfcr]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"
