modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/Rivmun/SuperFancyCloudsRefabricated/issues"
license = "MIT"

[[mods]]
modId = "sfcr"
version = "${version}"
displayName = "SuperFancyClouds: Rearchitected"
authors = "Rimo"
credits = "Ami-Wishes"
description = '''
A client/server side mod makes your Minecraft sky full of more stereoscopic and dynamic clouds.
'''
logoFile = "icon.png"

[[dependencies.sfcr]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sfcr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sfcr]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"
