org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

loom.ignoreDependencyLoomVersionValidation=true

mod.group=com.rimo
mod.id=sfcr
mod.name=SuperFancyClouds:
mod.version=2.9.4
mod.description=A client/server side mod makes your Minecraft sky full of more stereoscopic and dynamic clouds.
mod.author=Rimo
mod.contributor=ami-wishes
mod.sources=https://github.com/Rivmun/SuperFancyCloudsRefabricated
mod.issues=https://github.com/Rivmun/SuperFancyCloudsRefabricated/issues
mod.homepage=https://www.curseforge.com/minecraft/mc-mods/superfancyclouds-refabricated
mod.modrinth=https://modrinth.com/mod/superfancyclouds-refabricated
mod.mcmod=https://www.mcmod.cn/class/9053.html
mod.license=MIT
mod.icon=icon-
