# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2-pre-3
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=2.9.2-mc26.2-pre
maven_group=com.rimo
archives_base_name=sfcr

# Dependencies
fabric_version=0.150.2+26.2
cloth_config_version=26.1.154
yacl_version=3.9.3+26.2-fabric
mod_menu_version=20.0.0-alpha.1
