# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-snapshot-1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.9.3-mc26.3-snp
maven_group=com.rimo
archives_base_name=sfcr

# Dependencies
fabric_version=0.153.1+26.3
cloth_config_version=26.2.155
yacl_version=zjZChhNt
mod_menu_version=20.0.0-alpha.1
