mod.id="sfcr"
mod.name="SuperFancyClouds:Rearchitected"
mod.version="1.9.4.2"
mod.description="A client/server side mod makes your Minecraft sky full of more stereoscopic and dynamic clouds."
mod.author="Rimo"
mod.contributor="ami-wishes"
mod.sources="https://github.com/Rivmun/SuperFancyCloudsRefabricated"
mod.issues="https://github.com/Rivmun/SuperFancyCloudsRefabricated/issues"
mod.homepage="https://www.curseforge.com/minecraft/mc-mods/superfancyclouds-refabricated"
mod.modrinth="https://modrinth.com/mod/superfancyclouds-refabricated"
mod.mcmod="https://www.mcmod.cn/class/9053.html"
mod.license="MIT"
mod.icon="icon.png"

deps.distanthorizons-api="7.1.0"
deps.distanthorizons="3.0.3-b-"
distanthorizons_min_version="2.4.5"

["1.21.1-fabric"]
deps.minecraft="1.21.1"
version_range="=1.21.1"
deps.fabric="0.18.4"
deps.arch-api="13.0.8"
deps.cloth="15.0.140"
deps.fabric-api="0.116.9+1.21.1"
deps.modmenu="11.0.1"
deps.particlerain="v4-beta.10+1.21.1-fabric"
deps.sereneseasons="10.1.0.1"
deps.fabric_seasons="2.4.2-BETA+1.21"
particlerain_min_version="4.0.0-beta.8"
fabricseasons_min_version="2.4.2-beta"

["1.21.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="1.21.1"
version_range="[1.21.1]"
deps.neoforge="21.1.219"
neoforge_min_version="21.1"
deps.arch-api="13.0.8"
deps.cloth="15.0.140"
deps.particlerain="v4-beta.10+1.21.1-neoforge"
deps.sereneseasons="10.1.0.3"
particlerain_min_version="4.0.0-beta.8"

["1.20.1-fabric"]
deps.minecraft="1.20.1"
version_range=">=1.20 <=1.20.1"
deps.fabric="0.17.1"
deps.arch-api="9.2.14"
deps.cloth="11.1.136"
deps.fabric-api="0.92.6+1.20.1"
deps.modmenu="7.0.0"
deps.particlerain="v4-beta.10+1.20.1-fabric"
deps.sereneseasons="9.1.0.2"
deps.fabric_seasons="2.4.2-BETA+1.20"
particlerain_min_version="4.0.0-beta.8"
fabricseasons_min_version="2.4.2-beta"

["1.20.1-forge"]
loom.platform="forge"
deps.minecraft="1.20.1"
version_range="[1.20,1.20.1]"
deps.forge="1.20.1-47.1.0"
forge_min_version="46"
deps.arch-api="9.2.14"
deps.cloth="11.1.136"
deps.particlerain="v4-beta.10+1.20.1-forge"
deps.sereneseasons="9.1.0.2"
particlerain_min_version="4.0.0-beta.8"
mod.contributor="ami-wishes, Llamalad7 (MixinExtras embedded)"
deps.mixinextras="0.5.0"

["1.19.2-fabric"]
deps.minecraft="1.19.2"
version_range="=1.19.2"
deps.fabric="0.17.1"
deps.arch-api="6.6.92"
deps.cloth="8.3.134"
deps.fabric-api="0.77.0+1.19.2"
deps.modmenu="4.1.1"
deps.particlerain="3845717"
deps.fabric_seasons="2.3+1.19"
particlerain_min_version="2.0"
fabricseasons_min_version="2.3"

["1.19.2-forge"]
loom.platform="forge"
deps.minecraft="1.19.2"
version_range="[1.19.2]"
deps.forge="1.19.2-43.2.8"
forge_min_version="43"
deps.arch-api="6.6.92"
deps.cloth="8.3.134"
deps.sereneseasons="8.1.0.24"
mod.contributor="ami-wishes, Llamalad7 (MixinExtras embedded)"
deps.mixinextras="0.4.1"

["1.18.2-fabric"]
deps.minecraft="1.18.2"
version_range="=1.18.2"
deps.fabric="0.17.1"
deps.arch-api="4.12.94"
deps.cloth="6.5.133"
deps.fabric-api="0.77.0+1.18.2"
deps.modmenu="3.2.5"
deps.fabric_seasons="1.4-BETA+1.18"
fabricseasons_min_version="1.4-beta"

["1.18.2-forge"]
loom.platform="forge"
deps.minecraft="1.18.2"
version_range="[1.18.2]"
deps.forge="1.18.2-40.2.0"
forge_min_version="40"
deps.arch-api="4.12.94"
deps.cloth="6.5.133"
deps.sereneseasons="7.0.0.15"
mod.contributor="ami-wishes, Llamalad7 (MixinExtras embedded)"
deps.mixinextras="0.3.5"

["1.16.5-fabric"]
deps.minecraft="1.16.5"
version_range="=1.16.5"
deps.fabric="0.17.1"
deps.arch-api="1.32.68"
deps.cloth="4.17.132"
deps.fabric-api="0.42.0+1.16"
deps.modmenu="1.16.23"
deps.particlerain="3420025"
deps.fabric_seasons="1.2-BETA"
particlerain_min_version="1.4.0"
fabricseasons_min_version="1.2-beta"

["1.16.5-forge"]
loom.platform="forge"
deps.minecraft="1.16.5"
version_range="[1.16.5]"
deps.forge="1.16.5-36.2.39"
forge_min_version="36"
deps.arch-api="1.32.68"
deps.cloth="4.17.132"
deps.sereneseasons="4.0.1.130"
mod.contributor="ami-wishes, Llamalad7 (MixinExtras embedded)"
deps.mixinextras="0.2.0"
