deps.minecraft=1.21.11
version_range=[1.21.11]

deps.neoforge=21.11.42
neoforge_min_version=21.11

deps.cloth=21.11.153

deps.distanthorizons-api=6.1.0
deps.distanthorizons=3.0.2-b-1.21.11
deps.sereneseasons=21.11.0.4
deps.iris=1.9.4+1.21.10-fabric

distanthorizons_min_version=2.4.5

loom.platform=neoforge
