deps.minecraft=26.1.2
version_range=[26.1,)

deps.neoforge=26.1.2.29-beta
neoforge_min_version=26.1

deps.cloth=26.1.154

deps.distanthorizons-api=6.1.0
deps.distanthorizons=3.0.2-b-26.1.2
deps.sereneseasons=26.1.2.0.2
deps.iris=1.10.9+26.1

distanthorizons_min_version=2.4.5

loom.platform=neoforge
